# Generated by Django 3.2.12 on 2022-03-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='matchObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('gameStart', models.CharField(max_length=100)),
                ('gameEnding', models.CharField(max_length=100)),
                ('gameDuration', models.CharField(max_length=100)),
                ('participants', models.TextField()),
                ('teams', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='playerObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100)),
                ('summonerid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('rankedSolo', models.TextField()),
                ('championStatistics', models.TextField()),
                ('matchs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='runesObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runeId', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='matchTimeLineObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allEvents', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticorequests.matchobject')),
            ],
        ),
    ]
