# Generated by Django 3.2.14 on 2022-07-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticorequests', '0002_championlistjson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='championListJson',
        ),
    ]
