# Generated by Django 3.2.14 on 2022-07-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticorequests', '0003_delete_championlistjson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemobject',
            old_name='itemId',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='matchobject',
            old_name='gameDuration',
            new_name='game_duration',
        ),
        migrations.RenameField(
            model_name='matchobject',
            old_name='gameEnding',
            new_name='game_ending',
        ),
        migrations.RenameField(
            model_name='matchobject',
            old_name='gameStart',
            new_name='game_start',
        ),
        migrations.RenameField(
            model_name='matchobject',
            old_name='matchId',
            new_name='match_id',
        ),
        migrations.RenameField(
            model_name='matchtimelineobject',
            old_name='allEvents',
            new_name='all_events',
        ),
        migrations.RenameField(
            model_name='playerobject',
            old_name='rankedSolo',
            new_name='ranked_solo',
        ),
        migrations.RenameField(
            model_name='playerobject',
            old_name='summonerid',
            new_name='summoner_id',
        ),
        migrations.RenameField(
            model_name='runesobject',
            old_name='runeId',
            new_name='rune_id',
        ),
    ]
